// <auto-generated />
namespace ApplicationDevelopment.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class stafftrainertraineemodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(stafftrainertraineemodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106130047196_staff,trainer,trainee model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
